/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Report that the program is running.
         *
         *     This answer depends on nothing: no key, no database, no other service. That
         *     is the point. A container manager restarts the program when this route stops
         *     answering, so anything it depended on could cause restarts for a reason that
         *     has nothing to do with the program being alive.
         *
         *     Returns:
         *         A fixed status of "ok".
         */
        get: operations["healthz_api_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Report whether the program can generate a map yet.
         *
         *     Today that comes down to one thing: whether a key for the language model is
         *     configured. Without it the program still runs, still serves the stored
         *     example map, and still says so honestly here rather than failing later with
         *     an error the user cannot interpret.
         *
         *     Args:
         *         settings: The program's settings. Supplied by the web framework, which
         *             lets a test replace them without touching the real environment.
         *
         *     Returns:
         *         Whether the program is ready, and whether a model key is configured.
         */
        get: operations["readyz_api_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/about": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * About
         * @description Report the product name and the running version.
         *
         *     Returns:
         *         The name and the version of this build.
         */
        get: operations["about_api_about_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * About
         * @description What this program calls itself, and which build is running.
         */
        About: {
            /**
             * Name
             * @description The product name, always "Katalyst".
             */
            name: string;
            /**
             * Version
             * @description The version of the running build, such as 0.1.0.
             */
            version: string;
        };
        /**
         * Health
         * @description The answer to "is this program running?".
         */
        Health: {
            /**
             * Status
             * @description Always "ok". If the program cannot answer at all, nothing is returned.
             * @constant
             */
            status: "ok";
        };
        /**
         * Readiness
         * @description The answer to "can this program do its job yet?".
         */
        Readiness: {
            /**
             * Status
             * @description Reads "ready" when everything needed to generate a map is configured, and "not_ready" when something is missing.
             * @enum {string}
             */
            status: "ready" | "not_ready";
            /**
             * Model Key Present
             * @description Whether a key for the language model is configured. The key itself is never included in this answer.
             */
            model_key_present: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_api_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readyz_api_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
    about_api_about_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["About"];
                };
            };
        };
    };
}
