/**
 * What this copy of the program can do, with the one field the generated
 * description does not carry yet.
 *
 * `GET /api/readyz` says whether a model key is configured and, now, which
 * examples can be played back from a recording and when each was made. The
 * browser's own description of the server is generated from the server's
 * description of itself, and that file is regenerated by the half of this stack
 * that owns the route — so, exactly as the eight stream events are, the new field
 * is written out by hand here until it is.
 *
 * **Where the day on the first screen comes from.** Not from the stream: the day
 * a recording was made travels on the receipt, and the receipt arrives at the
 * *end* of a run, long after the first screen needs to print it. So the readiness
 * answer carries it, and the browser reads it from there — never from a file
 * name, never from a build date, never from its own clock.
 *
 * **`recording_date`, and never `recorded_on`.** It is the same day the
 * recording's header carries and the same day the receipt carries, so it keeps
 * one name in all three places: one fact, one word, nothing to translate between.
 */

import type { Readiness as Described } from "../api/client";

/** One example this build can play without a key. */
export interface RecordingSummary {
  /** Which stored example it is, matching the first screen's card. */
  readonly example: string;
  /** The day it was made, as the map writes a day: `2026-09-18`. */
  readonly recording_date: string;
}

/** The readiness answer as this build reads it. */
export interface Readiness extends Described {
  /**
   * The examples this copy can play. Empty when nothing has been recorded.
   *
   * **Only the ones that would actually play.** A file the engine could not
   * read is not on this list, so a card that offers a run is a card that has
   * one — the list and the offer cannot come apart.
   */
  readonly replayable: readonly RecordingSummary[];
  /**
   * One plain sentence per file in the recordings folder this engine could not
   * read.
   *
   * **A bad file never hides the good ones**, and it never hides itself either.
   * A recording is a committed file that outlives the code that wrote it, so
   * meeting an old one is ordinary rather than exceptional — and a reviewer who
   * put a recording in the folder and sees three cards instead of four is owed
   * the reason, in the server's own words, rather than left to guess whether
   * they put it in the wrong place.
   */
  readonly unreadable: readonly string[];
}

/**
 * Read the list of recordings off the readiness answer, whether or not the
 * generated description knows about it yet.
 *
 * A server that does not send the field is a server with nothing to replay,
 * which is exactly what an empty list says — so there is no third state to
 * invent and nothing here guesses.
 *
 * @param answer The readiness answer, exactly as it arrived.
 */
export function withRecordings(answer: Described): Readiness {
  const said = answer as Partial<Readiness>;
  return {
    ...answer,
    replayable: Array.isArray(said.replayable) ? said.replayable : [],
    // A server that does not send this is a server with nothing it could not
    // read, which is what an empty list says. Nothing here guesses at a third
    // state and nothing here writes a sentence of its own.
    unreadable: Array.isArray(said.unreadable) ? said.unreadable : [],
  };
}
